### ISSUE TITLE
Complete compatibility with Jenkins configuration-as-code

### ISSUE THREAD

**Issue by ahallermed** [jenkinsci/publish-over-ssh-plugin#301]
### What feature do you want to see added?

I wish to be able to fully configure the publish-over-ssh-plugin via the configuration-as-code-plugin.
Currently, only the following parameters of the common configuration are supported via configuration as code.

```yaml
  sshPublisher:
    commonConfig:
       disableAllExec: false,
       encryptedPassphrase: ...
       key: ...
       keyPath: ....
```

Desired behaviour would be that also the ssh server could be added via yaml configuration:

```yaml
  sshPublisher:
    commonConfig:
       disableAllExec: false,
       encryptedPassphrase: ...
       key: ...
       keyPath: ....
    hostConfig:
      - name: "first server"
        hostname: 123.123.123.123
       username: myuser
       ...
     - name: "second server"
       ....
```

Links from configuration-as-code-plugin, how to make the extension completely compatible:
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/PLUGINS.md

That would help me a lot, as I have several servers to configure and your plugin is perfect for my usecase.
Thank you in advance.
